services:
  app:
    build: .
    container_name: express_app
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017/meetings?authSource=admin
      JWT_SECRET: your-secret-key
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - database

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  dbdata:
    driver: local
